spring.application.name=thisaraprinters
# Max file size for a single request
spring.servlet.multipart.max-file-size=100MB


# Max total request size for a multi-part request (files + form data)
spring.servlet.multipart.max-request-size=100MB

# Tomcat max sizes to prevent connection resets
server.tomcat.max-swallow-size=100MB
server.tomcat.max-http-form-post-size=100MB
# Source - https://stackoverflow.com/a/54405341
# Posted by AbstractVoid, modified by community. See post 'Timeline' for change history
#Retrieved 2026-05-27, License - CC BY-SA 4.0

spring.servlet.multipart.resolve-lazily=true
#set file upload count 
server.tomcat.max-part-count = 200


#db connection details
spring.datasource.url=jdbc:mysql://localhost:3306/thisaraprinters
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Run data.sql to seed tables after JPA has created/updated the schema
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#set serialization off for empty beans
spring.jackson.serialization.fail-on-empty-beans=false

#set email configurations
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yasiru2000@gmail.com
spring.mail.password=zacanuaoxqebmvly
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
